name: tv_series
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  sqflite: ^2.0.2
  http: ^0.13.4
  dartz: ^0.10.1
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  provider: ^6.0.2
  build_runner: ^2.1.7
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17

flutter:
  assets:
    - cert/_.themoviedb.org.pem
