name: movie
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  http: ^0.13.4
  equatable: ^2.0.3
  dartz: ^0.10.1
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  provider: ^6.0.2
  sqflite: ^2.0.2
  firebase_crashlytics: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.2
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:
